### ISSUE TITLE
Classifications

### ISSUE THREAD

**Issue by alexandregrignon** [bimstandards/bimstandards#59]
URL page : http://bimstandards.fr/standards/classifications/
URL source : https://github.com/bimstandards/bimstandards/blob/gh-pages/_standards/classifications.md

**Todo :**
- [x] introduction sur les classifications applicables au BIM
- [x] liste Uniformat II 2015
- [ ] liste Omniclass - Table 13
- [ ] propriétés correspondante dans l'IFC
- [ ] implémentation Allplan
- [ ] implémentation Archicad
- [ ] implémentation Revit
- [ ] exemple SMC ?
